### ISSUE TITLE
How to execute an executable after packaging ?

### ISSUE THREAD

**Issue by rthangam** [vercel/pkg#1005]
I need to package sql (Oracle) executable in a node js project. The executable will be invoked by the node js project. I could see that sql is getting packaged, but when it is getting invoked it fails because the path doesn't exist, how this issue can be fixed ?

/users/rthangam/src/apps/sqlcl/bin/sql is the executable path, but after packaging it tries to use

/snapshot/rthangam/src/apps/sqlcl/bin/sql which doesn't exist

**Comment by lselden** [comment]
Look at the [Snapshot filesystem](https://github.com/vercel/pkg#snapshot-filesystem) section in the docs - basically use `process.execPath` instead of `__dirname` to resolve your relative path.

If you're trying to package the executable as an `asset` then you'll need to copy it to disk before trying to execute it - the os can't read pkg's virtual file system. Keep in mind antivirus scanners make detect this as suspicious activity.

**Comment by rthangam** [comment]
Thanks but the issue is even when i pack as an asset it is not working. Let's say the relative path is ./tool/bin/sql when i pack it 
there is no problem but when i execute the path changes to ./snapshot/tool/bin/sql and that is where it breaks since this path doesn't exists

**Comment by miraclx** [comment]
> That's probably the case, pkg probably just intercepts fs calls to `/snapshot` and resolves it with internal data.
>
> For this use case, the first time your executable is run, you can get readable streams to the assets (binaries) you want, and write them into an external staged directory (maybe even a temp dir), or if you embedded a zip file, extract that into your staged dir.
>
> Then you can spawn the executables with that path on your actual local filesystem.
>
> To speed things up (especially at startup), maybe don't use a random temp dir for each run.
>
> So you can use the assets from the previous extraction. (to save having to extract on every run)

_Originally posted by @miraclx in https://github.com/vercel/pkg/issues/1001#issuecomment-775071226_
