### ISSUE TITLE
no support for node version 15

### ISSUE THREAD

**Issue by arminbarazesh** [vercel/pkg#1008]
using latest version of "pkg" installed, when trying to build my app with node version 15, got this response:

> pkg@4.4.9
> Targets not specified. Assuming:
  node15-linux-x64, node15-macos-x64, node15-win-x64
> Error! No available node version satisfies 'node15'    <<<< issue

it seems node version 15 is not supported yet! there are many optional chaining cases in my code, so i have to use node version later than 14.

**Comment by lselden** [comment]
Node version support is tracked over in the [pkg-fetch](https://github.com/vercel/pkg-fetch/issues) repo. pkg tends to target LTS releases instead of the old-numbered node.js releases (it'd be a lot of work to keep up with a moving target codebase).

You can try forking pkg + pkg-release to contribute to the development process if you're into C++, or use a transpiler like Typescript or Babel.

**Comment by chuanqisun** [comment]
Thanks @lselden for explaining. I had the same question. Just curious, what is the overhead for fetching non-LTS node versions? I was imagining that it's a semver variable that controls which version to be fetched and if you let user specify that, there would be no additional cost. I might be ignorant of the caveats so please correct my understanding if I'm wrong.

Thank you for upkeeping this great tool!

**Comment by hipstersmoothie** [comment]
pkg does custom builds of node. it's easier to manage if it's only LTS versions
