### ISSUE TITLE
Serving dynamically generated files? (e.g. Swagger)

### ISSUE THREAD

**Issue by JohnLevander** [vercel/pkg#1010]
When my node app runs using the normal node server, there are resources that are generated/added at runtime (specifically I'm talking about Swagger classes like swagger-ui.css).  That is, these files do not ever exist in my directory structure, but they are available via http://mysite//swaggerui/swagger-ui.css.

When I run, instead, as an executable generated by pkg, everything works great except the generated/dynamic files referenced above.  They fail to load.  I've read the README several times, but I'm new to node and it's possible I am missing something.

Is there a way I can serve these dynamic files using pkg?

**Comment by lselden** [comment]
I'm guessing you're using swagger-ui-express, so you're ending up triggering [this line](https://github.com/swagger-api/swagger-ui/blob/master/swagger-ui-dist-package/absolute-path.js) at some point, which uses `__dirname`. That will use the current [Snapshot path](https://github.com/vercel/pkg#snapshot-filesystem), rather than looking at a disk file location.

1. If the problem is it isn't finding `.css` or `.js` files that already exist then you may need to specify them in the `assets` part of the pkg config.
2. If these are dynamically generated then it may be that swagger is trying to cache files resolving against `__dirname`, which will point it to the Snapshot filesystem - you'll have to change some config to have it write to an absolute path somewhere.

**Comment by JohnLevander** [comment]
Thanks.
