### ISSUE TITLE
Error! Error: EBUSY: resource busy or locked, open

### ISSUE THREAD

**Issue by salsan** [vercel/pkg#1044]
- Windows 10 Version 2004 ( Build SO 19041.804)
- Node v14.15.5
- pkg 4.4.9

My code 
`console.log("Hello Wolrd!");`

When try execute pkg

> >pkg hello.js  
> > pkg@4.4.9
> > Targets not specified. Assuming:
>   node14-linux-x64, node14-macos-x64, node14-win-x64
> > **_Error! Error: EBUSY: resource busy or locked, open 'D:\Progetti\obs theme utility\hello-win.exe'_**

**Comment by Aymkdn** [comment]
I received the same error. After closing SublimeText, it finally worked.

**Comment by zhzLuke96** [comment]
I know this issue is stale, but I did have the same problem and I found a simple solution

my environment
- windows10
- vscode v1.69.2
- node v16.15.0
- pkg v5.8.0

solution:
I added the /dist (compiled output folder) folder to files.exclude in `VScode Workspace Setting` , error never again

like this (.vscode/settings.json)
```json
{
    "files.exclude": {
        "/dist": true
    }
}
```

So, my guess is that the problem is mainly due to special system calls from IDE causing occupy file resources, and only windows has this problem

**Comment by georges-ph** [comment]
@Aymkdn I resolve it by fully restarting my PC.

For real this should be fixed. If I compile it the first time it compiles with no problems. But if I change something in the code and compile it again I get that error. And it doesn't work until fully restarting the pc
