### ISSUE TITLE
[support] windows 7

### ISSUE THREAD

**Issue by sayem314** [vercel/pkg#1156]
How do I support windows 7? node v14.4 works but I would like to use the latest version.

As per the error message, passing `NODE_SKIP_PLATFORM_CHECK=1` should work but I can't pass env variables to the final exe.

![photo_2021-04-29_22-30-01](https://user-images.githubusercontent.com/14138401/116585670-71f4d480-a93a-11eb-96e9-b36ff348c0b7.jpg)

**Comment by Hypfer** [comment]
Nodejs dropped support for Windows 7 due to it becoming EOL in early 2020:

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list

Previous versions of pkg-fetch at some point patched-out this check:
https://github.com/vercel/pkg-fetch/blob/3394388dcca379e29d910ac7b4aa74385721fcb2/patches/node.v14.0.0.cpp.patch#L526-L537


So you'd need to add that to the newer nodejs patches and build the base binaries yourself if you need W7 and have faith that it will actually run
https://github.com/nodejs/node/blob/52e4fb5b23157222d85b9275f7ccdfa88fe88d0f/src/node_main.cc#L34-L50

**Comment by jesec** [comment]
^
