### ISSUE TITLE
Follow XDG cache directory standard by default

### ISSUE THREAD

**Issue by rightaway** [vercel/pkg#1225]
The cache directory by default should use `~/.cache/pkg` according to the XDG Base Directory Specification rather than `~/.pkg-cache` which doesn't follow any standard. Most applications today use this standard and pkg should do the same to be compliant and keep the home directory clean.

https://github.com/vercel/pkg/issues/222 from many years ago also requested it.

> It would be great if this module followed the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Instead of placing the cache directory in the home directory it should be placed in the OS specific appropriate directory. Getting the correct directory is easy with a module like [env-paths](https://github.com/sindresorhus/env-paths). This, among other things, allows a user to specify a directory in which they want all applications to look for their user configurable setting files and keep their home directory clean.

**Comment by rightaway** [comment]
What's the point of this?

**Comment by jesec** [comment]
Noted, but can't be implemented before the next major release.

**Comment by btsimonh** [comment]
Notes on my experience of extracting stuff from a VFS for use as dependencies, pkg style:

On Windows, I use ProgramData/<companyname>/ to cache pkg-like files from a virtual FS.
This works fine on most systems.  It breaks down in two specific circumstances:
1/ multiple users.  If the first ever launched app creates the <company name> folder, other users have read/write/create but NOT UPDATE rights.  This then means that if the app is run by a different user, and needs to change a file, it will fail.  The solution is to ensure that at folder create (from pkg), it is created with update rights for all users, so that cached application specific files can be updated by any user.
2/ Officious IT rules.  In some corporate cases, ProgramData is not a valid executable location by default.  e.g. I bring down ffmpeg, and it will not execute from this folder.  The easy solution is to add a rule to allow files in <companyname> folder to be executed.  Note that .node and .dll files seem not to need extra rules to work.

I was using temp, and that also worked fine except on linux and OSX, where it got cleaned periodically (i.e. I lost my dependencies whilst the app was running!).  The programData equivalents work fine on linux and osx now without issues.

For pkg, I would suggest something like .cache/pkg/appname/ as the root for a certain app, just to separate possibly conflicting data?

The use of a written standard like the one mentioned above seems a good solution, but we'd need a humanised description detailing where it would be on Windows & OSX.
BUT.  in my case my data is application specific, not 'user specific' which is what the above spec defines.  For MOST people, there would be no difference, and disk is cheap.
