### ISSUE TITLE
module aliase support

### ISSUE THREAD

**Issue by zhex900** [vercel/pkg#1231]
This is duplicated by #249 #896 but I cannot find a solution to those issues. Can one help?

````
//package.json
  "_moduleAliases": {
    "common": "dist/common/src"
  },
  "pkg": {
    "scripts": "dist/**/**/*.js", // I don't really understand this part
    "assets": "dist/**/*", // I don't really understand this part
    "targets": [
      "node14-win-x64"
    ],
    "outputPath": "build"
  }
````

````
// tsconfig.json
{
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "skipLibCheck": true,
    "esModuleInterop": true,
//    "noImplicitAny": true,
    "sourceMap": true,
    "outDir": "dist",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*"],
      "common/*": ["../common/src/*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}

````

**Comment by darrensapalo** [comment]
Have you read and tried this?

https://github.com/vercel/pkg/issues/249#issuecomment-643117032

**Comment by zhex900** [comment]
I tried to read it. I couldn't make much sense of it. What exactly should I Ido?

**Comment by darrensapalo** [comment]
It would help if you can share what you do understand, so that I (or others) can figure out where to begin to help you.

If you're unfamiliar with how module aliases work and the compilation from ts (with aliases) to js, this might be a good article to start with: https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353

The comment I linked describes that when `pkg` is used to package it into an executable file, it uses the `dist` folder, which contains the builds (in javascript). The javascript still contained the aliases- so we want to revert that using `ef-tspm`.

**Comment by Rafatcb** [comment]
@darrensapalo Do you know how to find a custom entrypoint for [ef-tspm](https://github.com/ef-carbon/tspm)? It throws an error for me:
> File not found: 'C:\project\dist\app.js'

But that is because the file is at `C:\project\dist\src\app.js`.

----

Also, when I move the `app.ts` to root, it throws another error:

> JavaScript parsing error: Unexpected token (C:\project\dist\src\someFile.js:6:13): 'rn { ...msg'

The line content is `return { ...msg, value };`. It doesn't support spread operator. My `ts.config.json` has `ES2020` as target, I had to change to `ES6` in order to make it work.

I think ef-tspm may have other issues, since the repository is archived and the last release is from 2018.

Does someone have another solution? 😞

**Comment by Inrixia** [comment]
I've been banging my head against a wall for hours trying to get compilation working with this. I'm almost at the point of refactoring away from aliases to get it to work.

This really should be supported
