### ISSUE TITLE
Urgent help, no response to package EXE file

### ISSUE THREAD

**Issue by takeleav** [vercel/pkg#1303]
I try to use PKG to package the JS file of node.js,
But the packaging process is always stuck in the screenshot I sent. What's the problem
![6YYT$68{F$_QX@F4AVA{}~6](https://user-images.githubusercontent.com/38717820/132127587-3ca5244f-4ad1-4f44-96d5-5ba62bfbfc79.png)

**Comment by takeleav** [comment]
Tried to wait for 20 minutes, no response, please help me solve this problem, thank you!

**Comment by takeleav** [comment]
Can someone help me T.T

**Comment by jesec** [comment]
pkg has to fetch patched Node.js binaries from GitHub. 

https://github.com/vercel/pkg-fetch/releases/tag/v3.2

You have to ensure that it is possible to connect to Internet in your environment. If you wish to use proxies, you can utilize `HTTP_PROXY` and `HTTPS_PROXY` env variables.

**Comment by I2rys** [comment]
First, to test If your pkg is working, don't use the argument -t. Just do the standard way like this:
`pkg tt.js`

If it works, that means It's probably because you didn't put the correct value on the argument -t.

For more information about pkg you should read It's documentation. https://npmjs.com/package/pkg
