### ISSUE TITLE
Changing package icon make it unusable

### ISSUE THREAD

**Issue by Flymeth** [vercel/pkg#1894]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

19.2.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node18

### Describe the Bug

So for after compile my nodejs project into a .exe with pkg, I wanted to make a custom icon for it.
So created my own .ico file with png sizes of 16, 32, 64, 128 and 256, and set them for my .exe with RessourceHacker.

After that, I saved the .exe file and tryied to launch my .exe and nothing appened except the following message that displays just before the console crash:
"Pkg: Error reading from file."

### Expected Behavior

I expect just to be able to change the .exe icon without corrupt it.

### To Reproduce

1. Make an icon (.ico format)
2. Apply it to the .exe with the help of RessourceHacker
3. Save it
4. Launch the edited .exe

**Comment by Flymeth** [comment]
![image](https://user-images.githubusercontent.com/54219876/227160857-de2f93aa-78b7-4010-bffc-d3a2ddfb1089.png)

And this doesn't work even if I set the exact same images dimentions in the .ico (see the screenshot above) as this comment say:
https://github.com/vercel/pkg/issues/151#issuecomment-376520519

**Comment by Flymeth** [comment]
I get the same problem that mentionned here https://github.com/vercel/pkg/issues/91#issuecomment-863591246 when I try to edit the base executable's icon in the .pkg-cache

**Comment by Kruithne** [comment]
Take a look at `resedit`, which comes in both a CLI and a package. The problem is that when you change the icon via resource editing, you're changing the location of the embedded source code, which prevents `pkg` from being able to find it.

`resedit` comes with the option `--no-grow` (and --allow-shrink is disabled by default) which are designed to handle this issue specifically.

https://github.com/jet2jet/resedit-js-cli
https://github.com/jet2jet/resedit-js

**Comment by Flymeth** [comment]
![image](https://user-images.githubusercontent.com/54219876/229916643-cb448950-4bde-4f54-bcb4-93bbeef7fab6.png)
I've tried to replace icon with resedit with the --no-grow parameter, but it crashed, even if the size of my .ico file is well lesser than the original node .ico file (see on the screenshot)
![image](https://user-images.githubusercontent.com/54219876/229917271-9e4b57e6-cb61-4629-b2af-b52054661fd0.png)

**Comment by Kruithne** [comment]
> ![image](https://user-images.githubusercontent.com/54219876/229916643-cb448950-4bde-4f54-bcb4-93bbeef7fab6.png)
> 
> I've tried to replace icon with resedit with the --no-grow parameter, but it crashed, even if the size of my .ico file is well lesser than the original node .ico file (see on the screenshot)
> 
> ![image](https://user-images.githubusercontent.com/54219876/229917271-9e4b57e6-cb61-4629-b2af-b52054661fd0.png)
> 
> 

So you need to make sure that you're replacing the correct icon in the resource table otherwise it will be appending it as a new resource thus always increasing the size of the resource table, which makes it crash if --no-grow is passed.

For PKG executables, the icon is named "1", so to replace it do --icon 1,path/to/icon.ico

**Comment by Flymeth** [comment]
Thanks a lot for your fast reply.
It worked!
