### ISSUE TITLE
Assets detection not working depending on path module naming

### ISSUE THREAD

**Issue by jgoux** [vercel/pkg#202]
Hello,

I transpile my code using babel before packaging it.

So my `import path from 'path'` turns to `_path2.default`.

It has the effect of not detecting my assets when I use the `join` function.

I also try importing path like this : `const path2 = require('path')` and it doesn't work either.

Do you think it would be possible to make the detection a little bit smarter so we can transpile or use custom names for the module?

**Comment by cancerberoSgx** [comment]
I'm using pck with browserify for solving this kind of problems since browserify is smarter and have well-defined rules and plugins for require(), something like this:

```
browserify myappindex.js --no-bundle-external  --no-builtins  -o bundle.js
pkg -t node8-linux -c pkg.json -o execfile bundle.js
```
I recommend pkg maintainers not to tackle the require() problem and rely on browserify-like tools for building a bundle file like this - pkg should only put focus on packaging to executable files the bundle.
