### ISSUE TITLE
Unexpected error in pkg/prelude/bootstrap.js on Mac OS X

### ISSUE THREAD

**Issue by atn832** [vercel/pkg#205]
I used Etcher-cli (packaged with pkg) to erase and install an OS on an SD card. When it is about to erase the SD card, the program crashes with the following stack trace:

```
events.js:160
throw er; // Unhandled 'error' event
^

Error: UNEXPECTED-15
at readFromSnapshot (pkg/prelude/bootstrap.js:493:16)
at Object.fs.read (pkg/prelude/bootstrap.js:510:5)
at ReadStream._read (fs.js:1998:6)
at ReadStream.Readable.read (_stream_readable.js:348:10)
at fs.js:1963:10
at zalgoSafe (pkg/prelude/bootstrap.js:207:10)
at pkg/prelude/bootstrap.js:424:9
at FSReqWrap.oncomplete (fs.js:123:15)
```

The build I used is https://github.com/resin-io/etcher/releases/download/v1.1.2/Etcher-cli-1.1.2-darwin-x64.tar.gz, on Mac OS Sierra 10.12.6.

I initially posted the issue on Etcher's github, and they redirected me to pkg (https://github.com/resin-io/etcher/issues/1697).

**Comment by dhruvio** [comment]
Any update on this?

**Comment by taoshaoye** [comment]
Any update on this?

**Comment by lancety** [comment]
see this @atn832  @dhruvio

**Comment by jackkav** [comment]
I had this issue but caused by something else.
I was using node-libcurl and pkg was failing silently during the recursive copy from /snapshot/... to /tmp/pkg/...
I found the cause was a node_module mismatch in my project that was causing node-libcurl to install a specific version of tslib inside its own node_module directory. When the `copyFolderRecursiveSync` function of bootstrap.js encountered the node_modules folder as it was iterating over dist, node_modules, and lib it stopped recursing before it could reach the lib folder when the node_libcurl.node binary was contained.
I solved it by adding a matching tslib version to the package.json calling pkg. 
Ref: https://github.com/Kong/insomnia/pull/6001
