### ISSUE TITLE
cannot resolve __dirname with pkg

### ISSUE THREAD

**Issue by yamini1994** [vercel/pkg#219]
I want to use variables with require statement but pkg is throwing warning while creating an exe

Warning Cannot resolve 'path.resolve(__dirname, './server')'
  D:\RPT_CodeGenerator\rpt-ejs-generator\rpt-ejs\discover-schema\sql\discover-schema.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.

my code looks something like this

var app = require(path.resolve(__dirname, './discover-schema/sql/server'));
 
i tried writing the file in package.json but still it is not working

package.json
"pkg":{
"scripts" : "discover-schema/**/*.js"
}

can you please help me with this.

**Comment by zachsa** [comment]
I also have this problem. I suspect that there are better ways to resolve paths, but is there a reason that joining a relative path to _dirname would ever not work?

**Comment by cancerberoSgx** [comment]
I'm using pck with browserify for solving this kind of problems since browserify is smarter and have well-defined rules and plugins for require(), something like this:

```
browserify myappindex.js --no-bundle-external  --no-builtins  -o bundle.js
pkg -t node8-linux -c pkg.json -o execfile bundle.js
```
I recommend pkg maintainers not to tackle the require() problem and rely on browserify-like tools for building a bundle file like this - pkg should only put focus on packaging to executable files the bundle.
