### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by simon-p-r** [vercel/pkg#305]
Hi 

I keep getting above error when requiring a native module, I have tried hard-coding path and using suggested techniques in readme to fix it but no joy so far.  Is there something simple I am missing? 

Thanks

**Comment by simonhochrein** [comment]
Does your .node file rely on any DLLs? If so the DLLs must be in the system PATH or the same directory. Otherwise check if the version of node used by `pkg` is the same as the version of `node`. A good way to check would be putting ```console.log(`Version: ${process.version}`);``` in your js file and checking if the output is the same with or without compilation.

**Comment by chengsu** [comment]
+1

**Comment by chengsu** [comment]
I use `cmakejs` to build addon gets this error, but `node-gyp` builds the same code and works fine.

**Comment by simon-p-r** [comment]
Yes I use cmakejs to build as well

**Comment by knopkem** [comment]
Same issue using cmake-js here as well

**Comment by chengsu** [comment]
I never meet this issue on linux using cmake-js, seems windows dedicated.

**Comment by zhex900** [comment]
> Same issue using cmake-js here as well

Did anyone get a solution for this?
