### ISSUE TITLE
[Question] is it possible to create a man page?

### ISSUE THREAD

**Issue by j-brown** [vercel/pkg#338]
Currently, I am able to create a man page for my CLI application using npm's "man" property (inside the package.json).

This works well when an end user install my application globally with "npm install APP -g".

I am unsure how to create man pages for a packaged binary using pkg, however. I've looked over the docs and other issues for some references, but to no avail. Any insight would be appreciated.

**Comment by Clement-TS** [comment]
If I'm right, `npm` is not only designed to package node.js apps... You may also target a pkg binary in the "main" section of the new "package.json" of your app.

Or you can directly use `npm install node@8` within your package, so you don't need *pkg*:

https://twitter.com/housecor/status/962347301456015360

**Comment by j-brown** [comment]
Little confused by that comment @Clement-TS.

npm supports man pages: https://docs.npmjs.com/files/package.json#man

It works when I globally install the node module. I was curious if pkg supported it. If I'm missing something let me know!

**Comment by Clement-TS** [comment]
I'm wanted to say (tell me if I'm wrong) pkg is not intended to replace npm, but it helps you bundling your scripts with the node.js interpreter itself. It replaces "node.js", not "npm".

From that point, if you want your users to keep the *npm man pages*, I assume you have two options:

1. Create another package.json which points at your bundled pkg binary, and adds the extra doc (but npm will still be required on the system)
2. Install node.js as a npm dependency instead of using pkg (but npm will still be required on the system) as explained in my link
