### ISSUE TITLE
How to specify the version of a generated execution program?

### ISSUE THREAD

**Issue by sopaco** [vercel/pkg#390]
How to specify the version of a generated execution program?

**Comment by shirtleton** [comment]
If you're looking to specify a node version, just make sure you're using the node version you want before you run `pkg` with `node -v`
Otherwise,
You can rename the built file with the version in your `package.json` with something like this in a build script:
`VERSION=$(node -p \"require('./package.json').version\") && mv -f dist/your-executable-file dist/your-executable-file-$VERSION`

Or you can assign version to pretty much anything.

**Comment by CatTail** [comment]
Another to do that is using `pkg . --output build/experiment-validator-$npm_package_version`, any key can be referenced, beginning with `$npm_package_` and adding an underscore for every level you go down.

**Comment by CatTail** [comment]
Another way to do that is using pkg . --output build/program-$npm_package_version, any key can be referenced, beginning with $npm_package_ and adding an underscore for every level you go down.
