### ISSUE TITLE
windows .exe file executing error

### ISSUE THREAD

**Issue by dashng** [vercel/pkg#470]
```
Error: Please install sqlite3 package manually
at new ConnectionManager (C:\snapshot\cnt-tool\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:31:15)
```

**Comment by FabianTe** [comment]
This happens because sequelize does not itself install any database driver.

Looks like you want to use sqlite3. So ideally you have to `npm install --save sqlite3` to install the module and you are done. Probably you are missing that module in you package.json and a CI job does not install it?

Problem is, sqlite3 is a native c++ addon. Once you add that, pkg will have trouble dealing with it: https://github.com/zeit/pkg/issues/690
