### ISSUE TITLE
What is the relationship of pkg to enclose?

### ISSUE THREAD

**Issue by kethinov** [vercel/pkg#49]
Does pkg supersede enclose? There appears to be a relationship between the two projects, but I see that the github repo for enclose hasn't been updated in a while. Also pkg appears to be fully open source, whereas enclose is (partially?) proprietary.

Would be useful to have an explainer on this somewhere to reduce confusion.

Also, wow this project is cool. 😄

**Comment by rmharrison** [comment]
Maybe at a brief project history section in the README.md, to eventually be included on the github pages site?

**Comment by abacaj** [comment]
Looks like the use cases are copied from Enclose.

**Comment by pmq20** [comment]
😄 Also checkout [node-compiler](https://github.com/pmq20/node-compiler) with differences being,

| Project   | Differences                                                                                                                                                                                                                                                                                           |
|-----------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [pkg](https://github.com/zeit/pkg)       | Pkg hacked `fs.*` API's dynamically in order to access in-package files, whereas Node.js Compiler leaves them alone and instead works on a deeper level via libsquash. Pkg uses JSON to store in-package files while Node.js Compiler uses the more sophisticated and widely used SquashFS as its data structure. |
| [EncloseJS](http://enclosejs.com/) | EncloseJS restricts access to in-package files to only five `fs.*` API's, whereas Node.js Compiler supports all `fs.*` API's. EncloseJS is proprietary licensed and charges money when used while Node.js Compiler is MIT-licensed and users are both free to use it and free to modify it.                    |
| [Nexe](https://github.com/nexe/nexe)      | Nexe does not support dynamic `require` because of its use of `browserify`, whereas Node.js Compiler supports all kinds of `require` including `require.resolve`.                                                                                     |
| [asar](https://github.com/electron/asar) | Asar uses JSON to store files' information while Node.js Compiler uses SquashFS. Asar keeps the code archive and the executable separate while Node.js Compiler links all JavaScript source code together with the Node.js virtual machine and generates a single executable as the final product. |
| [AppImage](http://appimage.org/)  | AppImage supports only Linux with a kernel that supports SquashFS, while Node.js Compiler supports all three platforms of Linux, macOS and Windows, meanwhile without any special feature requirements from the kernel.                                                                                                                                                                                       |

**Comment by amritdevilo** [comment]
if the question has been answered, why not close this issue

**Comment by levrik** [comment]
@amritdevilo I don't see where the initial question was answered. Do I'm missing something?

**Comment by kethinov** [comment]
I think the answer was "yes." But I suppose it wasn't explicit. Reopening...
