### ISSUE TITLE
node-ffi issue

### ISSUE THREAD

**Issue by avalla** [vercel/pkg#523]
Hello, 
I cannot find any way to package a node application that uses [node-ffi](https://github.com/node-ffi/node-ffi) to access external libraries.

Here you can find an example:

https://github.com/avalla/issue-pkg-ffi

Thanks!!

**Comment by qmenoret** [comment]
Hey, we ran into the same issue lately, solution is just to:
- stop using __dirname (use `process.cwd()`)
- ship the dll next to the produced binaries
See https://github.com/zeit/pkg#detecting-assets-in-source-code

The problem here is that pkg tries to find the file inside of the snapshot filesystem, but it's still impossible to package a dll from what I know
