### ISSUE TITLE
Node app is headless when run in Ubuntu

### ISSUE THREAD

**Issue by alexanderson1993** [vercel/pkg#525]
In Ubuntu 18.04 Desktop, running the packaged Node app by double-clicking on the app causes the app to run in the background, completely headless with no way to close the app other than running a kill command. By contrast, on macOS and Windows, it opens up a terminal window and shows the stdout of the program. Closing the terminal window closes the app. Am I doing something wrong, or is that the expected behavior? By preference, I would like the Ubuntu version to open up terminal window when it is executed.

Worth noting: If the Node app is run from the terminal like `./my-app`, it runs in that terminal window with the output, exactly the way I would expect it to when double-clicking on it.

**Comment by philippejadin** [comment]
I confirm I have the same problem on latest mint. Anyone has an idea on how to get the terminal back ?

**Comment by AndoGhevian** [comment]
I wrote a package for this, maybe it can help you, I also wrote a usage example for **pkg**, here are the links - [OpenTerm](https://www.npmjs.com/package/open-term) and [Usage example with pkg](https://github.com/AndoGhevian/VT-pkg).

**Comment by Nashorn** [comment]
having same issue

**Comment by AndoGhevian** [comment]
Hey @Nashorn, I mentioned the package above - [OpenTerm](https://www.npmjs.com/package/open-term), its written for the same reason, to run cli-apps in different platforms with different terminal emulators, and i created a project [VT-pkg](https://github.com/AndoGhevian/VT-pkg#important-notes) with the exact thing that you want, so that apps not run headless, and in the important-notes section i clarify what i do, Maybe its not clear, or there are some bug that you noticed, tell me if so, i will fix it. Sorry for mention this again, its not an advertising:)) I just trying to help.
