### ISSUE TITLE
Error with experimental syntax pkg 4.3.5

### ISSUE THREAD

**Issue by bhirmbani** [vercel/pkg#590]
My plan is to package next app. I thought this related to babel and I installed `@babel/plugin-proposal-decorators"` but with no luck.

This is the error message:

Error! This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (14:0)
/Users/bm/Documents/personal-project/projectprojectname/node_modules/loaders.css/loaders.css

This is the command i use: 
`pkg . --targets node10-alpine-x64 --out-path pkg`

**Comment by abz53378** [comment]
Ok, I just created a small project to test and found this is caused by the incorrect `require()` method used in my script. It was totally irrelevant with the `decorators `, it's caused by pkg loaded the `css` and `less` as the js script, and there just are `@` in those style files.

As [the documents](https://github.com/zeit/pkg#config) mentioned, pkg will traverse dependencies automatically, no matter the file is set as an asset. 
So, ensure there is no `require(<any style file path>)` in your script(also the required scripts), and the problem will be resolved.

**Comment by sunnyBob** [comment]
I got the same error. Report in the bulma's scss...Could you help me ? @abz53378

**Comment by sunnyBob** [comment]
I had solved this error, it was caused by my dependencies having dependency of fontend, and that dependency's syntax is regarded as error

**Comment by avilaj** [comment]
Has anynone solved this? I'm also experiencing same issues.
`Error! This experimental syntax requires enabling the parser plugin: 'exportDefaultFrom' (13:7)
  /Users/jorgeavila/Documents/ec-ui-cms-bo/node_modules/ast-types-flow/lib/types.js`

**Comment by acgray** [comment]
Also seeing this with bulma.sass.  Is there any way to exclude it from the build?

**Comment by hipstersmoothie** [comment]
You should add those files as [assets](https://github.com/vercel/pkg#assets)
