### ISSUE TITLE
Can not restart executable from script launched by child process 

### ISSUE THREAD

**Issue by AlSharp** [vercel/pkg#591]
I created a child process from parent process with name nodepkg 

```
const script = spawn(
  './install', [],
  {
    cwd: process.cwd() + '/' + 'temp',
    detached: true,
    stdio: 'ignore'
  }
);
script.unref();
```

The child process executes the following script (not working, can not execute nodepkg):

```
sleep 1s
kill -9 $(pgrep nodepkg)
sleep 1s
mkdir ../old
mv ../nodepkg ../old/nodepkg.old
cp ./nodepkg ../nodepkg
cd ..
./nodepkg &
exit 0
```

But if I give nodepkg new name for example nodepkg1 everything is working:

```
sleep 1s
kill -9 $(pgrep nodepkg)
sleep 1s
mkdir ../old
mv ../nodepkg ../old/nodepkg.old
cp ./nodepkg ../nodepkg1
cd ..
./nodepkg1 &
exit 0
```

How to solve this issue? What I am trying to do is update my app with a new version. I can do a reboot, but I would like to have just run it as it is replaced.

**Comment by Daniel-Olivier** [comment]
Could you give a more specific error message? Does it fail to launch the process or does the process hang?

When you run the compiled binary from itself (or a child process) it simply runs Node.JS (this is so that child_process.fork works properly). If you want it to actually start a new instance of your script you have to pass it the path to your packaged app

The following would not launch another instance of the currently running app. It would start an instance of Node.JS in interactive mode
```javascript
console.log(process.argv[0]); // outputs: "/path/to/your/compiled/binary"
require('child_process').spawn(process.argv[0],[]);
```

The following would launch another instance of the currently running app
```javascript
console.log(process.argv[0]); // outputs: "/path/to/your/compiled/binary"
console.log(process.argv[1]); // outputs: "/path/to/main/javascript/file" (eg: "/snapshot/index.js")
require('child_process').spawn(process.argv[0],[process.argv[1]]);
```

This behavior is counter-intuitive but it means that packaged apps behave in exactly the same way as non-packaged apps (running process.argv[0] just launches Node.JS)

I am not sure if this would effect your specific case because technically it is not running itself (you replaced the binary) but maybe it thinks that it is because the paths match

Try running
```javascript
const path = require('path');
const path_to_entrypoint = path.resolve(require.main.filename); // you could also use process.argv[1] here

const script = spawn(
  './install.sh', [path_to_entrypoint],
  {
    cwd: process.cwd() + '/' + 'temp',
    detached: true,
    stdio: 'ignore'
  }
);
script.unref();
```

install.sh
```bash
sleep 1s
kill -9 $(pgrep nodepkg)
sleep 1s
mkdir ../old
mv ../nodepkg ../old/nodepkg.old
cp ./nodepkg ../nodepkg1
cd ..
./nodepkg1 $1 &
exit 0
```

**Comment by einsqing** [comment]
> I created a child process from parent process with name nodepkg
> 
> ```
> const script = spawn(
>   './install', [],
>   {
>     cwd: process.cwd() + '/' + 'temp',
>     detached: true,
>     stdio: 'ignore'
>   }
> );
> script.unref();
> ```
> 
> The child process executes the following script (not working, can not execute nodepkg):
> 
> ```
> sleep 1s
> kill -9 $(pgrep nodepkg)
> sleep 1s
> mkdir ../old
> mv ../nodepkg ../old/nodepkg.old
> cp ./nodepkg ../nodepkg
> cd ..
> ./nodepkg &
> exit 0
> ```
> 
> But if I give nodepkg new name for example nodepkg1 everything is working:
> 
> ```
> sleep 1s
> kill -9 $(pgrep nodepkg)
> sleep 1s
> mkdir ../old
> mv ../nodepkg ../old/nodepkg.old
> cp ./nodepkg ../nodepkg1
> cd ..
> ./nodepkg1 &
> exit 0
> ```
> 
> How to solve this issue? What I am trying to do is update my app with a new version. I can do a reboot, but I would like to have just run it as it is replaced.

How to solve this issue?

**Comment by Daniel-Olivier** [comment]
> How to solve this issue?

By passing the args of the current process to the new process

**Comment by introspection3** [comment]
same as https://github.com/vercel/pkg/issues/1866
