### ISSUE TITLE
Source Map support?

### ISSUE THREAD

**Issue by esamattis** [vercel/pkg#596]
Is there any way to use source maps with the generated executable to get stack traces mapped to the original sources when using Typescript or ncc?

**Comment by epeli** [comment]
After some experiments it appears that inline source maps work with the [`source-map-support`](http://npmjs.com/package/source-map-support) module.

Just set `inlineSourceMap` to `true` in `tsconfig.json` and put `require("source-map-support").install()` to the top of the entry file.

Also you need to compile the executable with the `--public` flag.

**Comment by zenozen** [comment]
I got it working with webpack. The source map is built with `devtool: source-map` and uploaded to sentry. Everything seems straightforward.

Option `--public` seems undocumented, but IMO it's essential since with it, the line and column number can be viewed in the stack trace.

One thing I need to hack around is the source map generated is something like `/snapshot/project/...`, where `project` is the name of folder that contains the project. Hence it's possible that this is not stable on different machines. I hacked around this by hooking and patching sentry's event object. But I think it can be better made if it's a stable path like `/snapshot/...` (no `project` part), if there's an option for that it would be great.

**Comment by jgehrcke** [comment]
We are working with `inlineSourceMap` set to `true` when compiling our TypeScript code and when not using pkg we get 'correct' stack traces (with TS line numbers) -- after pkg bundling, however, for some of our code all we see are bad stack traces (with JS line numbers). Still cannot tell for sure -- stack traces happening in the entry point module look right, but further down the dependency tree the source map information flow seems to get disrupted by the pkg build. Hah.

**Comment by yurtaev** [comment]
Workaround for me: `pkg --no-bytecode --public --options=enable-source-maps` + `devtool: 'inline-source-map'` for webpack.

**Comment by itslenny** [comment]
For me I just had to do `pkg --public` and include `source-map-support` package as @esamattis outlined above.

This worked WITHOUT inline source maps (using source map files) and no need for the `--options=enable-source-maps` flag.

You also need to make sure the `.map` files are actually being included in the executable. For this I just added them as assets in package.json like this...


```json
{
  "pkg": {
    "assets": [
      "build/**/*.js.map"
    ]
  }
}
```
