### ISSUE TITLE
how does it work

### ISSUE THREAD

**Issue by ORESoftware** [vercel/pkg#612]
looks like the readme lacks a little section explain how it works.
for example, I can't figure out how it can work without the node executable being available.

**Comment by kabirbaidhya** [comment]
Hello Maintainers, I have the same question. 

I'm trying to understand how pkg works internally and what does it do to produce a binary. I checked  through issues, README and Q&A threads but nowhere can I find anything regarding that.

The same question has been asked at [other](https://stackoverflow.com/questions/51669770/how-does-zeit-pkg-bundle-my-node-application) [places](https://www.reddit.com/r/node/comments/aoi5k4/question_about_zeit_pkg/) too; but there's no clear answer.

This is important for us as users to know so that we're able to find the right use cases and can confidently [use this](https://github.com/zeit/pkg/issues/265) to fit our needs. Right now  the docs is very limited and this is not explained.

**Comment by leerob** [comment]
https://github.com/vercel/pkg/issues/1065
