### ISSUE TITLE
Package coffescript codebase

### ISSUE THREAD

**Issue by heipei** [vercel/pkg#635]
Hey Zeit folks,

I haven't found anything documenting this, so here's my question: Is it possible to package a project written in CoffeeScript? I get this when I point pkg to an index.js:
```
> pkg@4.3.7
> Error! Unexpected character '#' (1:1)
  [...]/server/app.coffee
```

The index.js looks like this and can be executed by Node directly:

```
require('coffeescript/register');
require('./app.coffee');
```

**Comment by myAlterX** [comment]
I got the same error trying to package an app requiring the [PSD.js](https://www.npmjs.com/package/psd) module which is written in coffeescript.

**Comment by heipei** [comment]
Any ideas how to get around this? ;)

**Comment by elidoran** [comment]
Need a way to exclude files seen in `require()` calls. 

I did a simple test with a single CS file and the error when packaging was due to it trying to treat the CS file as if it was a JS file. 

To prevent it from doing that I changed `require('./some.coffee')` to `require('./some' + '.coffee')` and that prevented it from trying to include it as a script. It instead included it as an Asset (because I configured it to include **.coffee files as assets). It warned about the require call saying that file wasn't being included (as a script). Which is fine because it was included as an asset, as desired.

Then, when I ran the executable it loaded the CS file properly.

If we could define an "exclude" configuration property (command line or in the package.json's pkg property) with glob(s) to exclude files from "scripts" then we could tell it to ignore the requires targeting files with the coffee extension. Seems like a simple "if require's string literal matches any of the exclude patterns then don't include it in 'scripts'". Be nice if the configuration could override its status from a "script" to an "asset" instead of just excluding it from "scripts". Which also leads me to thinking if we specify "**.coffee" in the "assets" config property then shouldn't that be enough to know the require string targeting a .coffee file is actually an asset?

Side note, I tried a require targeting a .json file and that worked fine. 

Of course, one solution for local CS files is to transpile them to JS files before running pkg. Is it possible to prebuild the entire PSD.js package before running pkg to build your app? I run the pkg command from a script via npm. If you did that then you could do a "pre..." script to transpile the CS first.
