### ISSUE TITLE
How to start the exe file as background process or service

### ISSUE THREAD

**Issue by ANANDHAKUMARS** [vercel/pkg#699]
Hi, I can able to convert my nodejs app to portable exe file. thanks a lot for the contribution.
When double clicking or starting from command prompt, application is started in a command prompt instead of background process. Please help me in creating the build as a background process. It would be great if it autostarts if machine is rebooted

**Comment by sharathbaddam** [comment]
Try NSSM - the Non-Sucking Service Manager, > https://nssm.cc/

Not sure if this is a perfect solution but it does the job.

**Comment by lselden** [comment]
I've used the (os-service)[https://github.com/nospaceships/node-os-service] package successfully with pkg.

**Comment by caligo-erik** [comment]
> I've used the [os-service](https://github.com/nospaceships/node-os-service) package successfully with pkg.
@lselden : How did you configure the cross-platform compilation?
I've just tried compiling from a Linux machine, but the application won't run on Windows?

**Comment by lselden** [comment]
I couldn’t get cross-compilation to work reliably. I think the trick is to
set your node-gyp environment variables correctly. Or just compile the
os-service add-on from windows, b/c I don’t think it’s engaged when run
from Linux (it just adds systemd files, vs having to call Windows service
APIs)

**Comment by caligo-erik** [comment]
Thanks for the information.
I will look into it, although for now I've found the workaround to use NSSM.
It works, the only problem is that I have to ship a second binary.

**Comment by introspection3** [comment]
> 我已经成功地将[os-service](https://github.com/nospaceships/node-os-service)软件包与pkg一起使用。

bad guy,nobody can use nssm or os-service.

https://github.com/nospaceships/node-os-service/issues/54

**Comment by iambighead** [comment]
> > 我已经成功地将[os-service](https://github.com/nospaceships/node-os-service)软件包与pkg一起使用。
> 
> bad guy,nobody can use nssm or os-service.
> 
> [nospaceships/node-os-service#54](https://github.com/nospaceships/node-os-service/issues/54)

I must be NOT one of your "nobody", i use NSSM so many times to run my app exe packaed by pkg.
On linux i will just use systemd service file to run them as service.
Please don't assume you as one person can represent everyone in the community

**Comment by introspection3** [comment]
> > > 我已经成功地将[os-service](https://github.com/nospaceships/node-os-service)软件包与pkg一起使用。
> > 
> > 
> > bad guy,nobody can use nssm or os-service.
> > [nospaceships/node-os-service#54](https://github.com/nospaceships/node-os-service/issues/54)
> 
> I must be NOT one of your "nobody", i use NSSM so many times to run my app exe packaed by pkg. On linux i will just use systemd service file to run them as service. Please don't assume you as one person can represent everyone in the community

pkg just love you??so you can ?

**Comment by introspection3** [comment]
> > > 我已经成功地将[os-service](https://github.com/nospaceships/node-os-service)软件包与pkg一起使用。
> > 
> > 
> > 坏家伙，没有人可以使用nssm或os-service。
> > [nospaceships/node-os-service#54](https://github.com/nospaceships/node-os-service/issues/54)
> 
> 我一定不是你的“无名小卒”之一，我多次使用 NSSM 来运行我的应用程序 exe 由 pkg 打包。 在 linux 上，我将只使用 systemd 服务文件将它们作为服务运行。请不要假设你作为一个人可以代表社区中的每个人

I can confirm pkg has something problems about using nssm.

**Comment by introspection3** [comment]
> > > 我已经成功地将[os-service](https://github.com/nospaceships/node-os-service)软件包与pkg一起使用。
> > 
> > 
> > bad guy,nobody can use nssm or os-service.
> > [nospaceships/node-os-service#54](https://github.com/nospaceships/node-os-service/issues/54)
> 
> I must be NOT one of your "nobody", i use NSSM so many times to run my app exe packaed by pkg. On linux i will just use systemd service file to run them as service. Please don't assume you as one person can represent everyone in the community

pkg just love you??so you can ? you will affect pkg team's judgment。
I can confirm pkg has something problems about service (windows)

**Comment by lselden** [comment]
In case it helps someone in the future: `winsw` is another option. `node-windows` uses it but that package is pretty out-of-date. There may be other ways of doing it, but I wrote up a gist that demonstrates using winsw.exe with pkg: https://gist.github.com/lselden/1e5c394a95828e42d07bc26da5e87070

Basic idea:
* Download [winsw](https://github.com/winsw/winsw) and put in the `bin` folder of your project (version 3 or 2 of winsw should work fine). You can also find by digging into the node-windows package contents
* Make sure that you include the exe file in the pkg `assets` config or by using the technique used in my gist (path.join(__dirname, 'bin/winsw.exe'). That way the exe file is stored within the pkg executable rather than externally
* Include an install flag in your executable that copies the winsw.exe to disk (rather than stored in pkg's virtual filesystem) and creates a config xml file
* Use winsw.exe install/uninstall etc. functionality to actually install as service
* Make sure you add a process.on('SIGINT') handler to stop your process, since that's what winsw uses as an indicator that the service should gracefully stop

My gist above includes some janky path testing to make sure it's actually able to find the executable (and fall back to just specifying by environment variable or relative path if you can't include in the pkg executable). Also an easy gotcha is that the working directory can get set to C:\windows\system32 when running as a service. Checking against process.execFile instead may be helpful
