### ISSUE TITLE
How to include another executable in the main executable?

### ISSUE THREAD

**Issue by chaitanyarahalkar** [vercel/pkg#700]
I am working on a project where my main binary requires me to include another binary.(PhantomJS binary). What are we supposed to specify in the package.json file?

**Comment by lselden** [comment]
You could probably pack it in the executable as an ["asset"](https://github.com/zeit/pkg#assets), however you'd need to copy it to the filesystem in order to actually run it. You're better off distributing (or [downloading](https://github.com/Medium/phantomjs)) it alongside your executable, because antivirus apps might detect bundled executables as a possible threat.
