### ISSUE TITLE
Not working for V4.4 on windows

### ISSUE THREAD

**Issue by infinityseth** [vercel/pkg#710]
I tried to make a package & installed the latest version 4.4, its trying to fecth some binaries from this url

https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v10.15.3-linux-x86

which is returning 404 and exiting process.

**Comment by RedAty** [comment]
For me too, no error message, just exit.
I created binaries on MacOS Mojave 10.14 for Linux,Windows,Macos and only Windows is crashing...
When i created binaries on WIndows 10 x64 for Linux,Windows,Macos, it was working on every system.

This Macos build issue repeated in earlier OS and PKG versions too, so this is not a new problem...

**Comment by TinHengWan-Derek** [comment]
I had the same issue, try to downgrade to V4.3.7 and it works for me

**Comment by danthegoodman** [comment]
I also came across this issue. It has to do with pkg's attempt to compile your app into binary into the exe instead of leaving it in source format.

Here are some workarounds I've found:

1. Find a way to build and supply your own version of node, compiled in 32-bit mode. I have no idea how feasible this is.
2. Build your pkg targeting a 32-bit machine from a windows machine with the 32-bit version of node
3. Stop distributing a 32-bit version of your package.

Alternatively, if you're comfortable with shipping your source code instead of having it compiled into a binary format, you can disable that feature by passing the following arguments to pkg:

```
--no-bytecode --public --public-packages '*'
```
