### ISSUE TITLE
4.4.0 winston library exits process without error raised

### ISSUE THREAD

**Issue by alessioerosferri** [vercel/pkg#732]
I used pkg for quite some time on version 4.3.8. My code does a require of the winston logging library.
`const logger = require("winston");`
Since 4.4.0 this does not work anymore and as soon as the require is fired, the process exits with exit code 0.

**Comment by FabianTe** [comment]
Having the exact same problem.
I am reverting to 4.3.8 right now since 4.4.0 also has problems building for 32-bit packages.

**Comment by alessioerosferri** [comment]
I thought I was the only one having this! Great to know someone else is experiencing the same issue. Hopefully this will get fixed soon. I can confirm that reverting to 4.3.8 works for me as well

**Comment by danthegoodman** [comment]
@alessioerosferri I've been digging through issues posting my workaround, and while you don't mention that you're building on mac and targeting an x86 version of your platform, I'm going to assume you are since downgrading back to 4.3.8 fixed your issue.

The issue i've found has to do with pkg's attempt to compile your app into binary into the exe instead of leaving it in source format.

Here are some workarounds I've found:

1. Find a way to build and supply your own version of node, compiled in 32-bit mode. I have no idea how feasible this is.
2. Build your pkg targeting a 32-bit machine from a windows machine with the 32-bit version of node
3. Stop distributing a 32-bit version of your package.

Alternatively, if you're comfortable with shipping your source code instead of having it compiled into a binary format, you can disable that feature by passing the following arguments to pkg:

```
--no-bytecode --public --public-packages '*'
```
