### ISSUE TITLE
pkg app on mac doesn't work on Windows

### ISSUE THREAD

**Issue by lincolnaleixo** [vercel/pkg#737]
When I pkg the app on Mac, it works great on Linux and Mac but not on Windows. If I pkg the app on Windows it works perfectly on Windows.

Is there anything I can do to make the pkg on mac working on Windows without the need to go to windows to pkg just for Windows?

Thanks

**Comment by TinHengWan-Derek** [comment]
Have you tried using pkg@4.3.7? I had that problem and seems like it works using that version

**Comment by danthegoodman** [comment]
I also came across this issue. It has to do with pkg's attempt to compile your app into binary into the exe instead of leaving it in source format.

Here are some workarounds I've found:

1. Find a way to build and supply your own version of node, compiled in 32-bit mode. I have no idea how feasible this is.
2. Build your pkg targeting a 32-bit machine from a windows machine with the 32-bit version of node
3. Stop distributing a 32-bit version of your package.

Alternatively, if you're comfortable with shipping your source code instead of having it compiled into a binary format, you can disable that feature by passing the following arguments to pkg:

```
--no-bytecode --public --public-packages '*'
```

**Comment by FabianTe** [comment]
Related to: https://github.com/zeit/pkg-fetch/issues/68

**Comment by robot110011** [comment]
yes, I'm using the last version. Thanks about the workaround but still don't fix the issue on building directly on MacOS. Still waiting for something to fix this.

**Comment by duqcyxwd** [comment]
> Have you tried using pkg@4.3.7? I had that problem and seems like it works using that version

The pkg@4.3.7 doesn't work for me but I think pkg@4.3.8 would be a solution.

**Comment by Nashorn** [comment]
Has there been a solution to .exe on windows not working?

**Comment by MichaelGaoX** [comment]
some problem.show pkg/prelude/bootstrap.js:1244 TypeError: argument fn must be a function  on Windows
