### ISSUE TITLE
Use without internet connection

### ISSUE THREAD

**Issue by Zoharos** [vercel/pkg#765]
Hello, 
How can I package a node app to exe offline?

**Comment by weagertron** [comment]
You will have to use a machine with an internet connection for the initial downloading part of this but once you have the binary you are good to go.

You can use the repository of PKG specific Node builds from [here](https://github.com/zeit/pkg-fetch/releases).

Once downloaded, you can place the file in your `pkg-cache` directory. On Windows this defaults to `C:\Users\<user>\.pkg-cache\v2.5` (replace v2.5 with whichever version of pkg-fetch that you got the binaries from). 

Make sure to rename the file to match the pattern of `fetched-<version>-<os>-<architecture>` an example of this would be `fetched-v10.4.1-linux-x64`. Otherwise PKG won't recognise it and will try to download it again.

Hope that helps!

**Comment by roberto-slopez** [comment]
I don't sure about your question, but if you don't use internet in your package, this can use without internet, in terms of generating it without internet, the comment above is an acceptable explanation of how to do it.
