### ISSUE TITLE
Is pkg still maintained?

### ISSUE THREAD

**Issue by Piccirello** [vercel/pkg#778]
I'm considering using `pkg` for a new project. Before doing so, I want to be sure pkg is being actively maintained. There currently seems to be an issue with the latest `pkg` version related to building Windows binaries (#686 #688 #762). This issue hasn't received much maintainer attention, which worries me a bit. There also haven't been any merged PRs since the last release.

This isn't a complaint in any way; I full recognize that this is an open source tool provided for free. I just want to be sure development is still active before integrating this into my build pipeline. Thanks for building this tool.

**Comment by AxelTerizaki** [comment]
I was asking myself the same question and am trying to switch to nexe, but I'm running into some issues I need to have fixed...

**Comment by jfhenon** [comment]
![image](https://user-images.githubusercontent.com/20402845/69479756-54484500-0e01-11ea-868a-e557efd8fde8.png)

scary.... I would not blame anyone to stop maintaining an open source package but can we just have a position?

**Comment by VoltanaDMG** [comment]
**Disclaimer:** Before you think I'm a developer of this module, **I'm not!**
---
The contributions looking fine for me because this module is only a bundler and if I'm right the developers don't plan to add any new features soon. So they invest only time for critical problems.

They're gonna spend a lot of more time in the other products, especially `hyper` and some business ones.
Also, keep in mind that `pkg-fetch` consumes a lot of time, it fetches a patched NodeJS version and those needs to be created & uploaded manually.

**IMO** you can use it, I use it too (for private & business products) and there aren't any big problems. But if you still have some concerns then go ahead and search for another `packager`.

**Comment by bergheim** [comment]
4.4.1 was just released, which (so far) makes 12.13.1 work fine for me. :)

**Comment by leerob** [comment]
https://github.com/vercel/pkg/issues/1065
