### ISSUE TITLE
Can not Load package.json in subdirectory !!!

### ISSUE THREAD

**Issue by parjom** [vercel/pkg#820]
I found the following problem using the azure-storage library.

I uploaded a sample example to github

[https://github.com/parjom/pkg-test](https://github.com/parjom/pkg-test)

pkg cannot read package.json in subdirectory

How can I solve it?

**Comment by PiyuKaka** [comment]
I am facing same issue . It would appreciated if anybody can look inti it and resolve this issue.
thanks.

**Comment by oFlo193o** [comment]
I'm also facing his issue. Seems like this ist also related to #851 .
@slprogrp came up with a workaround where the wrapper is replaced with the link to the correct file. Therefore you can avoid the package.json in the subdirectory.
But of course this only makes sense if you are not depending on both the node and browser version.
As I'm only using azure-storage with node and not in the browser i forked azure-storage and replaced  the statements.
Feel free to use my fork until this issue is fixed.
https://github.com/oFlo193o/azure-storage-node
