### ISSUE TITLE
pkg not respecting environment variable

### ISSUE THREAD

**Issue by jithinlal** [vercel/pkg#840]
I have a code like below

```
if (process.env.DB === MONGO) {
	TodoController = require('../controllers/mongo-todo.controller');
} else if (process.env.DB === FIREBASE) {
	TodoController = require('../controllers/firebase-todo.controller');
}

```
This is not working if I run pkg index.js, were index.js is the entry point.

Does conditional require not supported during pkg build?

**Comment by robintan** [comment]
@jithinlal I think the problem is because of the dynamic import on runtime. Try this
`
const MongoTodoController = require('../controllers/mongo-todo.controller');
const FirebaseTodoController = require('../controllers/firebase-todo.controller');
const TodoController = {
  MONGO : MongoTodoController,
  FIREBASE : FirebaseTodoController,
}[ process.env.DB ];
`

If it's not working, maybe you should try printing out the environment variables first for debugging purpose.
