### ISSUE TITLE
.exe is not portable

### ISSUE THREAD

**Issue by paulf98** [vercel/pkg#890]
If i start the generated .exe in my Project-folder everything works fine. When I move the .exe-file and run it again it just auto closes itself and does not work at all. 
I start the application with the following snippet which i have from Stackoverflow. In my package.json the bin entry points to this file:

```
var join = require('path').join
var childProcess = require('child_process');
var args = process.argv.slice(2);

 args.unshift(__dirname + '/../'); 

childProcess.exec('yarn start', (err, stdout) => {
if (err) console.log(err);
console.log(stdout);
}) 
```
There are similar issues which have still not been resolved.

**Comment by hktr92** [comment]
well... it IS portable, but your code won't work. it's because windows cmd (as any other in linux or mac os) looks for executables in a special variable called `PATH`, and if it's not there, it wont work.

to demonstrate this, write a simple hello world in c and try to execute it via js. then rename the hello world exe to something else and it will fail.

it's basic programming regarding dependencies.

if you, however, do need yarn in your project, simply embed it in your project.

**Comment by Nashorn** [comment]
Having same issue
