### ISSUE TITLE
Unable to build binary for Raspberry Pi Model B Rev 2

### ISSUE THREAD

**Issue by chainhead** [vercel/pkg#974]
I was going through this thread [on cross-compilation](https://github.com/vercel/pkg/issues/145#issuecomment-311150484) for building the binary for Raspberry Pi on Mac. I used the `examples/express` folder to test the cross-compilation.

This is what I get with `pkg package.json -t node8-linux-armv6 --no-bytecode`.

```bash
> pkg@4.4.4
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.16.2-linux-armv6  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v8.16.2-linux-armv6
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v8.16.2-linux-armv6"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v8.16.2-linux-armv6"}
> Building base binary from source:
  built-v8.16.2-linux-armv6
> Error! Not able to build for 'linux' here, only for 'macos'
```

So, I am not sure, if the thread on cross-compilation still holds.

For my project, when I tried to build with `pkg app/index.js -t node10-linux-armv6` I get lots of warning messages as `Failed to make bytecode`. If I use the `--no-bytecode` flag, I get an error as `--no-bytecode and no source code breaks final executable`.

I ran [`license-checker`](https://www.npmjs.com/package/license-checker) for my project and no module was flagged to _not_ have the license field.

Can you please advise how to build the binary for Raspberry Pi?

**Comment by chainhead** [comment]
Ignoring the warnings `Failed to make bytecode`, I ran the binary any way; only to get a `Segmentation fault`. What am I missing?

**Comment by Reda1000** [comment]
Easiest & Fastest way:
You can look a little around and you will probably find someone already compiling the binaries you need (i.e. https://github.com/vercel/pkg/issues/658). Place it in your pkg-cache-folder should do i.e. "~/.pkg-cache/v2.6/built-v12.18.1-linux-armv7".

Otherwise as stated here https://github.com/vercel/pkg/issues/605 this project is not capable of cross-cpu-compilation. Makes sure to have your macos running on armv6 - if that is anyhow doable. Be aware that this could take a while to compile.

Alternatively get a Raspberry and build it on there. Though it will run heavily like half a day or so to compile - once first compilation happened / pkg-cache holds necessary build it will be a lot faster.

**Comment by chainhead** [comment]
> You can look a little around and you will probably find someone already compiling the binaries you need (i.e. #658). Place it in your pkg-cache-folder should do i.e. "~/.pkg-cache/v2.6/built-v12.18.1-linux-armv7".
Firstly, it is [`armv6`](https://raspberrypi.stackexchange.com/a/83379/11789). Secondly, I have tried with the approach of downloading the binary and placing it in the cache location. That didn't work; see the post details.

> Alternatively get a Raspberry and build it on there.
Tried that too; 30 hours later got an error with `ld` command.

**Comment by Reda1000** [comment]
Could you describe how you downloaded and were you have put the Release Asset?

Have you tried with this Asset:
https://github.com/yao-pkg/pkg-binaries/releases/download/v1.0.0/fetched-v8.16.0-linux-armv6

**Comment by chainhead** [comment]
@Reda1000  hmm...I had downloaded from here https://github.com/yao-pkg/pkg-binaries/releases 

It was placed under the `.pkg-cache`, I think. Basically, I followed the instructions as mentioned in that repo.
